In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [8]:
data_clients = pd.read_excel("../data/default_of_credit_card_clients.xls")
data_clients.head(5)

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
1,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
2,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
3,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
4,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0

In [9]:
#forma
data_clients.shape

(30001, 25)

In [10]:
data_clients.info()

<class 'pandas.DataFrame'>
RangeIndex: 30001 entries, 0 to 30000
Data columns (total 25 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  30001 non-null  object
 1   X1          30001 non-null  object
 2   X2          30001 non-null  object
 3   X3          30001 non-null  object
 4   X4          30001 non-null  object
 5   X5          30001 non-null  object
 6   X6          30001 non-null  object
 7   X7          30001 non-null  object
 8   X8          30001 non-null  object
 9   X9          30001 non-null  object
 10  X10         30001 non-null  object
 11  X11         30001 non-null  object
 12  X12         30001 non-null  object
 13  X13         30001 non-null  object
 14  X14         30001 non-null  object
 15  X15         30001 non-null  object
 16  X16         30001 non-null  object
 17  X17         30001 non-null  object
 18  X18         30001 non-null  object
 19  X19         30001 non-null  object
 20  X20         30001 non-null  object
 21  X21         30001 non-null  object
 22  X22         30001 non-null  object
 23  X23         30001 non-null  object
 24  Y           30001 non-null  object
dtypes: object(25)
memory usage: 5.7+ MB

In [11]:
data_clients.describe()

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
count,30001,30001,30001,30001,30001,30001,30001,30001,30001,30001,...,30001,30001,30001,30001,30001,30001,30001,30001,30001,30001
unique,30001,82,3,8,5,57,12,12,12,12,...,21549,21011,20605,7944,7900,7519,6938,6898,6940,3
top,ID,50000,2,2,2,29,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
freq,1,3365,18112,14030,15964,1605,14737,15730,15764,16455,...,3195,3506,4020,5249,5396,5968,6408,6703,7173,23364

In [12]:
#valores nulos
data_clients.isnull().sum()

Unnamed: 0    0
X1            0
X2            0
X3            0
X4            0
X5            0
X6            0
X7            0
X8            0
X9            0
X10           0
X11           0
X12           0
X13           0
X14           0
X15           0
X16           0
X17           0
X18           0
X19           0
X20           0
X21           0
X22           0
X23           0
Y             0
dtype: int64

In [13]:
#valores duplicados
print(data_clients.duplicated().sum())
print("__________________________________________________________________________________________________")

0
__________________________________________________________________________________________________

In [14]:
data_clients.columns = data_clients.iloc[0]
data_clients = data_clients.drop(0)
data_clients.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object', name=0)

In [15]:
# Revisando el rango de datos de las variables y agrupando
for c in ["SEX","EDUCATION","MARRIAGE"]:
    print(c, data_clients[c].unique())

pays = [c for c in data_clients.columns if c.startswith("PAY_")]
for c in pays:
    print(c, sorted(data_clients[c].unique()))

SEX [2 1]
EDUCATION [2 1 3 5 4 6 0]
MARRIAGE [1 2 3 0]
PAY_0 [-2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8]
PAY_2 [-2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8]
PAY_3 [-2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8]
PAY_4 [-2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8]
PAY_5 [-2, -1, 0, 2, 3, 4, 5, 6, 7, 8]
PAY_6 [-2, -1, 0, 2, 3, 4, 5, 6, 7, 8]

In [16]:
data_clients["TOTAL_BILL"] = data_clients[["BILL_AMT1","BILL_AMT2","BILL_AMT3","BILL_AMT4","BILL_AMT5","BILL_AMT6"]].sum(axis=1)
data_clients["TOTAL_PAY"] = data_clients[["PAY_AMT1","PAY_AMT2","PAY_AMT3","PAY_AMT4","PAY_AMT5","PAY_AMT6"]].sum(axis=1)
data_clients["DEBT_RATIO"] = data_clients["TOTAL_BILL"] / data_clients["LIMIT_BAL"]           # que tanto usa del límite
data_clients["%_RATIO_PAYT"] = data_clients["TOTAL_PAY"] / data_clients["TOTAL_BILL"].replace(0, np.nan)  # qué % de la deuda es la que paga
data_clients["AVG_BILL"] = data_clients[["BILL_AMT1","BILL_AMT2","BILL_AMT3","BILL_AMT4","BILL_AMT5","BILL_AMT6"]].mean(axis=1)
data_clients["MAX_DEL_PAY"] = data_clients[["PAY_0","PAY_2","PAY_3","PAY_4","PAY_5","PAY_6"]].max(axis=1)   # máximo retraso registrado

In [17]:
data_clients.head(5)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month,TOTAL_BILL,TOTAL_PAY,DEBT_RATIO,%_RATIO_PAYT,AVG_BILL,MAX_DEL_PAY
1,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,1,7704,689,0.3852,0.089434,1284.0,2
2,2,120000,2,2,2,26,-1,2,0,0,...,1000,0,2000,1,17077,5000,0.142308,0.292791,2846.166667,2
3,3,90000,2,2,2,34,0,0,0,0,...,1000,1000,5000,0,101653,11018,1.129478,0.108388,16942.166667,0
4,4,50000,2,2,1,37,0,0,0,0,...,1100,1069,1000,0,231334,8388,4.62668,0.036259,38555.666667,0
5,5,50000,1,2,1,57,-1,0,-1,0,...,9000,689,679,0,109339,59049,2.18678,0.540054,18223.166667,0

In [18]:
#ahora vamos a determinr los valores atípicos
def detect_outliers(series):

    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = (series < lower) | (series > upper)

    return outliers.sum(), lower, upper

In [19]:
variables = ["LIMIT_BAL","TOTAL_BILL","TOTAL_PAY","DEBT_RATIO","AVG_BILL"]

for var in variables:
    
    count, low, high = detect_outliers(data_clients[var].dropna())

    print(f"{var}")
    print("outliers:", count)
    print("lower bound:", low)
    print("upper bound:", high)
    print("-------------")

LIMIT_BAL
outliers: 167
lower bound: -235000.0
upper bound: 525000.0
-------------
TOTAL_BILL
outliers: 2575
lower bound: -442219.75
upper bound: 813534.25
-------------
TOTAL_PAY
outliers: 2898
lower bound: -33555.875
upper bound: 73739.125
-------------
DEBT_RATIO
outliers: 29
lower bound: -5.741406791666667
upper bound: 10.048963541666666
-------------
AVG_BILL
outliers: 2575
lower bound: -73703.29166666667
upper bound: 135589.04166666666
-------------

In [20]:
#ahora exportamos la base de datos limpia
data_clients.to_csv("../data/credit_clients_clean.csv", index=False)